# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://h:pa6vnbvra37u4v1qp72tr5vehmo@ec2-54-227-252-69.compute-1.amazonaws.com:12769

development:
  adapter: async

test:
  adapter: async
